services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: runcloud-laravel
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - workspacenetwork
    environment:
      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    command: >
      sh -c "
        echo 'Waiting for MySQL...';
        until nc -z database 3306; do
          sleep 2;
        done;
        php artisan migrate:fresh --seed &&
        php artisan key:generate &&
        php artisan optimize:clear &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
  database:
    image: mysql:8.4.6
    container_name: runcloud-database
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - workspacenetwork

volumes:
  dbdata:

networks:
  workspacenetwork:
    driver: bridge
